version: "3"

services:
  web:
    build: .
    #command: nodemon -L --inspect=0.0.0.0:5858
    #keep alive
    command: bash -c "while true; do sleep 10; done"
    volumes:
      - ./app:/code
      - ./spec:/spec
    ports:
      - "8000:8000"
      - "5858:5858"
